application: godauction-ffs
version: 1
runtime: python27
api_version: 1
threadsafe: false 

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /css
  static_dir: css

- url: /js
  static_dir: js 

- url: /.*
  script: godauction.py
  login: required

libraries:
- name: jinja2
  version: "2.6"
